### ISSUE TITLE
PHPPwinty Discussion

### ISSUE THREAD

**Issue by atwright147** [hudster/PHPPwinty#4]
This isn't an actual issue, I would like to use this to discuss changes to the PHPPwinty Library

**Comment by atwright147** [comment]
## Things I would like to see in the PHPPwinty Library
1. Create a GitHub organisation
   This is free and would tie in with creating a PHP namespace.
   The organisation would simply be called Pwinty.
   You could then move all of the other language libs into this organisation.
   Ideally, this should be set up by Pwinty themselves to assure their ownership.
2. Decide minimum PHP version number requirement.
   I would suggest roughly 5.3 as this is the requirement for namespaces and Composer
3. Can we see documentation for the previous API version (Pwinty API 2.0)?
   So that we can see the differences between 2.0 and 2.1
   This will allow removal / changing of methods.

**Comment by atwright147** [comment]
@tomgallard

**Comment by hudster** [comment]
Yea I think this is one for Tom rather than me

**Comment by atwright147** [comment]
I only just found out his name :)
